# Generated by Django 2.2.4 on 2021-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnails_URLs', models.CharField(max_length=200, unique=True)),
                ('videoId', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
